# Generated by Django 4.0.2 on 2022-03-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
    ]
